### ISSUE TITLE
Workflow Problems

### ISSUE THREAD

**Issue by LanceMcCarthy** [MrYossu/Pixata.Utilities#2]
The current state of the CI-CD system is not operational due to errors claiming the _username is empty_ during a package restore.

@MrYossu I do not have access to the repository Settings page, please upgrade my collaborator status to the highest option so that I may add and remove secrets,

**Comment by MrYossu** [comment]
Please can you tell me how to do that? All I can see is a link to your user page. I can't see anywhere to set what access you have.

**Comment by LanceMcCarthy** [comment]
It appears to no be possible with a personal account. I will continue this discussion in the Telerik support case.

**Comment by MrYossu** [comment]
ok, thanks
